### ISSUE TITLE
关于合约调用C接口的英文长句表述晦涩难懂

### ISSUE THREAD

**Issue by DongAoMainland** [aitos-io/BoAT-X-Framework#100]
关于调用合约C语言接口的提请注意的英文语句，太长，整句话不好懂

在文档”BoAT User Guide"的章节“Header files and libraries”中，下面这段英文，请重新组织语言表述吧：
Pay special attention to the fact that although the contract function and C call interface function that change the state of the blockchain and do not change the state of the blockchain are very similar in prototype, the calling principles of the two are quite different.

**Comment by wsdhrtjl** [comment]
Rewrite the sentence both in English and Chinese
