### ISSUE TITLE
BoAT-X-Framework for Fibocom-FM650整合说明文档中描述存在问题

### ISSUE THREAD

**Issue by xymoc** [aitos-io/BoAT-X-Framework#1019]
在BoAT-X-Framework for Fibocom-FM650整合说明文档的第三章文件修改的第一段下存在以下描述：
`在头文件路径添加处新添以下内容：`
这段内容是否应该修改为
`在头文件路径处新添以下内容：`

**Comment by zzqAlex** [comment]
为防止引起歧义，已经修改为“在配置头文件目录的地方新添加以下内容：”
