### ISSUE TITLE
IOT设备原始数据上传到物联网云平台，这个云平台可以是自己公司的物联网平台吗？

### ISSUE THREAD

**Issue by keruiwang** [aitos-io/BoAT-X-Framework#1061]
原始数据上传到物联网平台（比如运营商的），但我们公司如果自己有物联网平台，如何兼容？

**Comment by FengHuan1999** [comment]
可以是物联网公司自己的云平台。
技术上上链和上云的链路可以分开，上链不影响原有上云的路由和既有业务。但在特殊情况下，如网络路由限制等因素，上链数据可能需经由物联网平台路由至区块链节点【设备无法直接访问区块链节点/服务】。由物联网平台转发上链数据时，方案需考虑数据在通过物联网平台等其他系统时的防篡改，脱密等问题，如经过某些密码学算法处理（哈希，签名等）。
