### ISSUE TITLE
"For Ethereum/Polygon/PlatON/PlatONE/FISCO BCOS:" is missing "Venachain"

### ISSUE THREAD

**Issue by hnngm** [aitos-io/BoAT-X-Framework#1067]
[wrong location](https://aitos-io.github.io/BoAT-X-Framework/#/en-us/BoAT_Overall_Design_en?id=transaction-data-structure-and-function-realization-list)

"For Ethereum/Polygon/PlatON/PlatONE/FISCO BCOS:"  缺少了“Venachain”

**Comment by zzqAlex** [comment]
“Venachain” has been added.
