### ISSUE TITLE
用户手册版本号

### ISSUE THREAD

**Issue by kitty0709** [aitos-io/BoAT-X-Framework#1084]
用户手册里的版本号是不是有误？

本文介绍BoAT IoT Framework SDK **2.x**的功能和使用方法。
本文的预期读者为集成BoAT IoT Framework SDK的客户。
本用户手册版本号为**1.0.0**。

**Comment by PanHH** [comment]
这里的版本号仅仅是用户手册的，跟SDK不保持一致。
