### ISSUE TITLE
BoAT_Solidity_Tool_User_Guide_cn.md文档在README.md中没有入口链接

### ISSUE THREAD

**Issue by xymoc** [aitos-io/BoAT-X-Framework#1127]
Solidity接口生成工具使用说明（[BoAT_Solidity_Tool_User_Guide_cn.md](https://github.com/aitos-io/BoAT-X-Framework/tree/boatiotsdk_2_0-dev/docs/zh-cn)）文档在README.md中没有对应的入口链接

**Comment by wsdhrtjl** [comment]
该文档还未完成。
