### ISSUE TITLE
BOAT_DISCOVERY_PEER_QUERY should not be TEST_MODE

### ISSUE THREAD

**Issue by Cavalierliu** [aitos-io/BoAT-X-Framework#1137]
ifeq ($(BOAT_TEST), TEST_MODE)
BOAT_TEST_FLAG = -fprofile-arcs\
                 -ftest-coverage

ifeq ($(BOAT_NODES_DISCOVER), OPEN)
BOAT_DISCOVERY_PEER_QUERY    = 1
else
BOAT_DISCOVERY_PEER_QUERY    = 0
endif
endif

**Comment by zt222** [comment]
This issue has been communicated and does not need to be modified.
