### ISSUE TITLE
在“Tool for Generating C Language Interface of PlatONE Smart Contract”，下面应该有个“生成Venachain智能合约C语言接口的工具”

### ISSUE THREAD

**Issue by hnngm** [aitos-io/BoAT-X-Framework#1151]
[问题位置](https://aitos-io.github.io/BoAT-X-Framework/#/en-us/BoAT_Overall_Design_en?id=tool-for-generating-c-language-interface-of-platone-smart-contract)
英文版与中文版比对，
在“Tool for Generating C Language Interface of PlatONE Smart Contract”，下面应该有个“生成Venachain智能合约C语言接口的工具”

**Comment by wsdhrtjl** [comment]
This issue has been fixed in branch 2.0
