### ISSUE TITLE
在"Please refer to the description of "send transaction" in"里的链接地址，没有指向对应的位置

### ISSUE THREAD

**Issue by hnngm** [aitos-io/BoAT-X-Framework#1152]
[错误位置](https://aitos-io.github.io/BoAT-X-Framework/#/en-us/BoAT_Overall_Design_en?id=the-process-of-creating-an-ethereum-transaction-using-boat)

在"Please refer to the description of "send transaction" in"里的链接地址，没有指向对应的位置

**Comment by wsdhrtjl** [comment]
If you click the same label for the second time, the redirect fails.
This link is working properly, please check.
