### ISSUE TITLE
BoAT-X-Framework/English Documents/BoAT Overall Desgin: Figure 4-1

### ISSUE THREAD

**Issue by aviico** [aitos-io/BoAT-X-Framework#122]
**Red Underline Spell Check In Image **

Figure 4-1 used in "BoAT Overall Design> BoAT Implementation Framework" has spell check red underlines.
**Suggestion:**
Edit figure to not have the corrections. 

**Screenshot:**
![image](https://user-images.githubusercontent.com/83634221/125191051-28353e00-e249-11eb-85f2-caef0a0dec49.png)

**Comment by wsdhrtjl** [comment]
Thank you for pointing that out. 

Most of them are C libraries or function names, They are not standard English word. So it's considered a spelling mistake by the editing software.

But, there shouldn't be any red lines in the uploaded image. They will be revised in the future.
