### ISSUE TITLE
BoAT User Guide-Software Dependency

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#1275]
**Describe the bug**
在Ubuntu下，可以使用apt install命令安装相应的包。在Cygwin下，使用Cygwin自带的Setup程序进行安装。

On Ubuntu, can use the apt install command to install the corresponding package. Under Cygwin, use the Setup program that comes with Cygwin to install.

Better translation could be:

On Ubuntu OS, you can use the apt install command to install the corresponding package. Under Cygwin OS, use the Setup program that comes with Cygwin to install.

**Comment by wsdhrtjl** [comment]
Cygwin is not an operate system. Mey be the sentence should be `On Ubuntu OS, you can use the apt install command to install the corresponding package. Under Cygwin, use the Setup program that comes with Cygwin to install.`.
