### ISSUE TITLE
BoAT Overall Design/Interface Layer-Unified description of "Hardware dependency layer"

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#143]
**Describe the bug**
The wallet interface of the interface layer is supported by the hardware dependent layer. For the description of the hardware dependent layer, please refer to Hardware dependency layer.

**To Reproduce**
We see "Hardware dependency layer"、“hardware dependent layer”、“hwdep”、“Hardware Dependency Layer” in the same article. Since it is a specific concept in our article, shall we use a unified description to replace the four different names.

**Comment by wsdhrtjl** [comment]
Thank you for pointing that out. Currently there is no hardware dependency layer in the program. All relevant instructions need to be rewritten. But it does need to be avoided.
