### ISSUE TITLE
BoAT System Requirements/Part One. Storage Requirements -"itself" better be replaced with "alone"

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#164]
**Describe the bug**
For Ethereum/PlatONE/FISCO BCOS, the storage requirements of the BoAT Framework (C language version) itself are:

**Precise Statement**
To enable Ethereum/PlatONE/FISCO BCOS capabilities, the storage requirements of the BoAT Framework (C language version) alone are:

**Comment by flyfft** [comment]
commit 8659103c74a523f9e8d823ea5a9f4e8c63534244 (HEAD -> boatiotsdk_2_0-dev, origin/boatiotsdk_2_0-dev)
Author: gary.xu@aitos.io <gary.xu@aitos.io>
Date:   Wed Jul 28 20:37:18 2021 +0800

**docs: clarify storage requirements #164**

    1. Replace

    For Ethereum/PlatONE/FISCO BCOS, the storage requirements of the BoAT Framework (C language version) itself are:

    with

    To enable Ethereum/PlatONE/FISCO BCOS capabilities, the storage requirements of the C-language BoAT Framework (excluding static or shared dependent libraries such as the C library) are:

    2. Replace

    For HyperLedger Fabric, the storage requirements of the BoAT Framework (C language version) itself are:

    with

    To enable HyperLedger Fabric capability, the storage requirements of the C-language BoAT Framework (excluding static or shared dependent libraries such as the C library) are:
