### ISSUE TITLE
中文版系统需求/操作系统和通信需求 描述可优化

### ISSUE THREAD

**Issue by zt222** [aitos-io/BoAT-X-Framework#177]
“BoAT Framework SDK（C语言版本）对操作系统没有特别要求，Linux和各种RTOS均可移植，但至少应支持以下能力：” 
其中，“至少应支持以下能力”，应该是后续的能力都是必需的，但是

“3. 支持按指定时长挂起线程（可选）。若不支持，则BoAT不支持超时或轮询功能，其他功能不受影响。”

“指定时长挂起线程”是可选的，非必需的，前后表述不恰当。

**Comment by PanHH** [comment]
Optional options are acceptable here.
