### ISSUE TITLE
full software implementation should not be hardware dependent.

### ISSUE THREAD

**Issue by DongAoMainland** [aitos-io/BoAT-X-Framework#193]
full software implementation should be hardware independent.

At the head of the section "Software Implementation of The Hardware Dependent Layer" in document of BoAT Overall Design，The sentence "BoAT SDK should provide a hardware-dependent full software implementation, so that BoAT can still run completely when the hardware cannot provide the required complete services." would make reader confused.
would it be better "BoAT SDK should provide a full software implementation which is hardware agnostic , so that BoAT can still run completely when the hardware cannot provide the required complete services."?

**Comment by wsdhrtjl** [comment]
This paragraph has been modified in PR #163 .
