### ISSUE TITLE
Hardware-dependent should be Hardware agnostic

### ISSUE THREAD

**Issue by DongAoMainland** [aitos-io/BoAT-X-Framework#194]
Hardware-dependent software should be wrong according to the context of "Hardware-dependent software"

The issue is at the head of second sentence in the first paragraph of section "Software Implementation of The Hardware Dependent Layer" in BoAT Overall Design 
would it be better "Hardware agnostic software"?

**Comment by wsdhrtjl** [comment]
This paragraph has been modified in PR #163 .
