### ISSUE TITLE
lThere should be spaces in the last line

### ISSUE THREAD

**Issue by Cavalierliu** [aitos-io/BoAT-X-Framework#221]
Commands
CYGWIN_BASE := C:\cygwin64  # Modify to actual path to Cygwin
BOAT_RM := $(CYGWIN_BASE)\bin\rm -rf
BOAT_MKDIR := $(CYGWIN_BASE)\bin\mkdir
BOAT_FIND := $(CYGWIN_BASE)\bin\find
Taking Windows 10 as an example, the method to add the search path to the Windows environment variable is:
a) Right-click on the Windows logo menu and select "System"
b) Click "System Information" on the "About" page
c) Click "Advanced System Settings" on the "System" page
d) Click "Environment Variables" in the "System Properties" page
e) Click "Path" in "System Variables" on the "Environment Variables" page, and click "Edit"
f) On the "Edit Environment Variables" page, click "New", add the bin path under the Cygwin installation directory, and make sure that the new path is located anywhere after the path %SystemRoot%\system32

**Comment by zt222** [comment]
![image](https://user-images.githubusercontent.com/81662688/128491643-0ad3fd6d-fb1a-4c06-9435-54d19f0daff6.png)

there are spaces here view on web
