### ISSUE TITLE
Step Start a new line

### ISSUE THREAD

**Issue by Cavalierliu** [aitos-io/BoAT-X-Framework#223]
Among them, the format of func_param_ptr follows the same rules as Step 3.

Example 2: PlatONE transaction structure -**Step 1 Call BoatPlatONETxInit() to initialize the transaction, and the transaction type field is set according to the actual transaction type.

-Step 2 Set transaction parameter:

**Comment by zt222** [comment]
there is no problem here,but  the format of "Step 3 " is Inconsistent
