### ISSUE TITLE
BoAT_Overall_Design_cn

### ISSUE THREAD

**Issue by kitty0709** [aitos-io/BoAT-X-Framework#240]
**Describe the bug**
This sentence is not fluency.
BoAT遵循层次化设计，由接口层，协议层，RPC层，供应商依赖层，通用工具和实用程序实现组成。

**Correct expression**
BoAT遵循层次化设计，由接口层，协议层，RPC层，供应商依赖层，通用工具层和实用程序组成。

**Comment by wsdhrtjl** [comment]
Generic tools are not a separate layer, they are functions that include format conversions and so on.
