### ISSUE TITLE
BoAT_Overall_Design_cn/some unclear descriptions

### ISSUE THREAD

**Issue by kitty0709** [aitos-io/BoAT-X-Framework#242]
**Describe the bug**
为何将boat SDK初始化放在钱包接口功能简述里？此处SDK是指钱包SDK还是Boat SDK?

钱包接口功能实现简述
SDK初始化/反初始化
SDK初始化：
在使用BoAT SDK之前应做SDK初始化，该接口执行的内容包括：
钱包列表初始化

**Comment by wsdhrtjl** [comment]
You can consider of the boat as a wallet.
