### ISSUE TITLE
libboatvendor.a    use   ecdsa   ecdsa_get_public_key65   ecdsa_sign_digest  ecdsa_verify_digest

### ISSUE THREAD

**Issue by alanmoleapfive** [aitos-io/BoAT-X-Framework#243]
lib/libboatvendor.a(boatplatform_internal.o): In function `BoatSignature':
boatplatform_internal.c:(.text.BoatSignature+0x2a): undefined reference to `g_log_level_name_str'
boatplatform_internal.c:(.text.BoatSignature+0xe1): undefined reference to `g_log_level_name_str'
lib/libboatvendor.a(boatplatform_internal.o): In function `BoatGetFileSize':
boatplatform_internal.c:(.text.BoatGetFileSize+0x16): undefined reference to `g_log_level_name_str'
boatplatform_internal.c:(.text.BoatGetFileSize+0x61): undefined reference to `g_log_level_name_str'
lib/libboatvendor.a(boatplatform_internal.o): In function `BoatWriteFile':
boatplatform_internal.c:(.text.BoatWriteFile+0x18): undefined reference to `g_log_level_name_str'
lib/libboatvendor.a(boatplatform_internal.o):boatplatform_internal.c:(.text.BoatWriteFile+0x68): more undefined references to `g_log_level_name_str' follow
collect2: error: ld returned 1 exit status

**Comment by wsdhrtjl** [comment]
Hello, can you tell me about the compilation environment used. And did you change any options before compiling? So we can locate the problem more easily.

**Comment by alanmoleapfive** [comment]
Hello, 
ubuntu18.04
amd64
git  clone  https://github.com/aitos-io/BoAT-X-Framework.git
cd  BoAT-X-Framework
make vendorlib
Did not make any changes

only   
keccak_256   is ok

use ecdsa ecdsa_get_public_key65 ecdsa_sign_digest ecdsa_verify_digest   not  ok

**Comment by wsdhrtjl** [comment]
Use `make vendorlib` alone will not compile successfully. 
'make all' is recommended.

**Comment by alanmoleapfive** [comment]
Already resolved
Comment out
BoAT-X-Framework/vendor/platform/linux-default/src/port_crypto_default/boatplatform_internal.c
All BoatLog
//BoatLog
