### ISSUE TITLE
riscv  Compile

### ISSUE THREAD

**Issue by alanmoleapfive** [aitos-io/BoAT-X-Framework#248]
I want to port the lib to the riscv environment. What should I do? I found out that "curl/curl.h" could not be found during compilation.

**Comment by wsdhrtjl** [comment]
This is a problem if your target compilation environment does not support curl. There are two options: porting the curl library or set curl disable.

Here are the steps that need to be ported:
1. Add a new folder under Vendor. Add the same target as the file name to the `PLATFORM_TARGET` of the primary makefile.  
2. Refer to other platforms under Vender, need to add `vendor/platfrom/<new folder>/scripts/gen.py`. Set the switch based on whether to port the curl library to the board.  
3.  Set this parameter based on the actual situation to `vendor/platfrom/<new folder>/external.env`.  
4. If curl library is not use, `vendor/platfrom/<new folder>/src/rpc/rpcinf.c`  needs to be implemented.

**Comment by alanmoleapfive** [comment]
thank you，very good
