### ISSUE TITLE
Add PlatON into the supported blockchain list

### ISSUE THREAD

**Issue by keruiwang** [aitos-io/BoAT-X-Framework#283]
Details:

SUPPORTED_LIST.md misses PlatON, which is already supported since [**BoAT-X-v2.0.7**](https://github.com/aitos-io/BoAT-X-Framework/releases/tag/BoAT-X-v2.0.7).

Add PlatON into the supported blockchain list.

**Comment by PanHH** [comment]
It is a same issue with #274.
