### ISSUE TITLE
put “Apache License 2.0”brief introduction at front page

### ISSUE THREAD

**Issue by keruiwang** [aitos-io/BoAT-X-Framework#284]
put Apache License 2.0 brief intoduction: _"A permissive license whose main conditions require preservation of copyright and license notices. Contributors provide an express grant of patent rights. Licensed works, modifications, and larger works may be distributed under different terms and without source code."_ at the front page,  so that commercial people could be easier to reach, detailed contents can keep it as it is now.

**Comment by flyfft** [comment]
To discuss:

As Apache License 2.0 is one of the most widely used open source licenses, it's unlikely to cause much confusion what this license is roughly about.

However the literal brief introduction is not a formal and legal claim given by Apache License 2.0. Instead, it's a informal explanation from Github, with a notice saying "*This is not legal advice. Learn more about repository licenses.*" on page [LICENSE](./LICENSE).

This explanation is subjected to change by Github. Thus, leaving a copy of the inaccurate introduction on the homepage might cause potential legal issues should Github change it someday.
