### ISSUE TITLE
Fibocom-L610 Chinese document modification suggestions

### ISSUE THREAD

**Issue by xymoc** [aitos-io/BoAT-X-Framework#296]
建议将以下内容修改为一句话：
2、拷贝 BoAT-X-Framework/vendor/platform/Fibocom-L610/L610RootDirCode/demo.c到L610平台代码根目录下。

3、拷贝 BoAT-X-Framework/vendor/platform/Fibocom-L610/L610RootDirCode/my_contract.cpp.abi.c到L610平台代码根目录下。

4、拷贝 BoAT-X-Framework/vendor/platform/Fibocom-L610/L610RootDirCode/my_contract.cpp.abi.h到L610平台代码根目录下。
示例：
2、将BoAT-X-Framework/vendor/platform/Fibocom-L610/L610RootDirCode/下的demo.c、my_contract.cpp.abi.c、my_contract.cpp.abi.h拷贝到L610平台代码根目录下。

**Comment by wsdhrtjl** [comment]
When the user operates, it is very easy to miss some file if three sentences are combined into one sentence. Therefore, no changes are made.
