### ISSUE TITLE
BoAT User Guide/English Docs/Grammar 

### ISSUE THREAD

**Issue by aviico** [aitos-io/BoAT-X-Framework#325]
Grammar Issues:
(BoAT Overall Design)

1) Rewriting suggestion- under "BoAT Design Goals":

**Original:**
As a middleware fusing Blockchain and IoT technologies, It should be easily and quickly transplanted into various IoT modules at the minimum cost of modification. The design of BoAT is based on these following principles:

**Suggestion:**
As a middleware **integrating** Blockchain and IoT technologies, **it** should be **efficiently** transplanted into various IoT modules **and at a minimum modification cost**. The design of BoAT is based **on the following principles**:

2) The paragraph under "The Position of BoAT SDK in The Entire Blockchain Network"-
The first sentence begins with "As a middleware connecting IoT devices and blockchain," while the first sentence of the prior paragraph also begins with "As a middleware fusing Blockchain and IoT technologies" ###, which may seem repetitive.

**Suggestion:**
Delete the whole sentence and leave only the image (Figure 3-1). The title+image+the description is enough.

**Comment by wsdhrtjl** [comment]
On the second point, although the sentences are repeated, but all the pictures are made up of description + picture + picture name. So, for consistency, don't change it.
