### ISSUE TITLE
202104080408-TM (Ubuntu)The version information that has been tested needs to be added

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#34]
问题描述：在编译SDK和使用之前，需要确保这些软件已经安装。在Ubuntu下，使用apt install命令安装相应的包。在Cygwin下，使用Cygwin自带的Setup程序进行安装。
问题修改建议：这里“Ubuntu”有没有版本限制，我看Github上其他项目会区分Ubuntu14.04/Ubuntu16.04等，我们也建议细化一下。
问题路径：BoAT 用户手册/SDK编译/软件依赖

**Comment by PanHH** [comment]
System version is generally not specified in most cases.
