### ISSUE TITLE
BoAT User Guide/ English Docs

### ISSUE THREAD

**Issue by aviico** [aitos-io/BoAT-X-Framework#347]
**Grammar Issue**

Under "BoAT IoT Framework SDK Architecture":
**Original:**
Hardware Dependent Components are ported components involving different hardware, such as cryptography accelerators, secure storage, random numbers, etc. This component needs to be ported according to specific hardware. SDK also provides a set of default Hardware dependent components witch implementations by software.

Suggestion:
Change "witch" to "with"

Also, this **last** sentence doesn't really make sense, if I understand correctly it should be:

"The SDK also provides a set of default hardware dependent components with an implementation method that is software-based."

**Comment by zzqAlex** [comment]
hi，aviico
This problem has been fixed according to your suggestion.
Thanks!
