### ISSUE TITLE
202104080412-TM (windows) The version information that has been tested needs to be added

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#35]
问题描述：在Windows下，SDK不支持在Cygwin以外的环境下编译。如果必须在Cygwin以外运行（例如以Windows为Build环境的交叉编译器），请参照3.5.2节对编译文件进行调整。
问题修改建议：这里“Windows”有没有版本限制，建议细化一下。
问题路径：BoAT 用户手册/SDK编译/软件依赖

**Comment by PanHH** [comment]
System version is generally not specified in most cases.
