### ISSUE TITLE
XinYi-XY1100 can support fabric and FISCO-BCOS?

### ISSUE THREAD

**Issue by xymoc** [aitos-io/BoAT-X-Framework#369]
I need to use xy1100 to connect to fabric blockchain, but I don't know whether the boat framework supports fabric.

**Comment by zzqAlex** [comment]
The fabric is too big, the onboard resources are not enough, and the onboard resources of XY1100 are very limited.

**Comment by xymoc** [comment]
I understand. Thanks.
