### ISSUE TITLE
BoatWalletCreate 函数参数不需要传递

### ISSUE THREAD

**Issue by Cavalierliu** [aitos-io/BoAT-X-Framework#385]
BoatWalletCreate(BOAT_PROTOCOL_ETHEREUM, NULL, &wallet_config, sizeof(BoatEthWalletConfig));
这个函数的最后一个参数是结构体的sizeof，这个结构体不包含动态数组，在编译的时候就确定了，不需要传递

**Comment by wsdhrtjl** [comment]
This function is provided for all types of blockchain wallets. Each blockchain wallet is not the same size, and this parameter is canceled, a separate function for each chain is need to be created. And that's not a good change.

**Comment by Cavalierliu** [comment]
可以放在BoatWalletCreate函数的内部进行判断是哪个链，然后进行sizeof的操作获取大小，如果以参数传进来，需要对这个大小进行一个 判断，如果用户传递的参数 不正确会导致不可预料的问题

**Comment by wsdhrtjl** [comment]
It is needed to add checks on input data

**Comment by wsdhrtjl** [comment]
Although this parameter is currently fixed, But the content of this parameter is intended for future extensions to support the variable length wallet option. Ethereum also has a way of invoking contracts using url like domain names. Therefore, the value of this parameter cannot be determined.

Therefore, this problem does not need to be modified.
