### ISSUE TITLE
boatiosdk-M5311-dev开发分支中的中文帮助文档链接返回404

### ISSUE THREAD

**Issue by DongAoMainland** [aitos-io/BoAT-X-Framework#400]
点击其中的帮助文档，得不到想要的readme信息，网页返回404提示

1、进入boatiosdk-M5311-dev分支；
2、选择“docs”目录；
3、点击下方readme.md中的“简体中文”链接
返回的是404

**Comment by PanHH** [comment]
我们在github上添加了动态生成文档网站的配置，文档网站运行时才会把.md文档转换成.html页面。这里直接点击.md文档中的链接会因为没有找到链接对应的资源而报“404”错误，在查看或编写.md文档时，应该忽略该问题。
BoAT documentation网站，可以点击[https://aitos-io.github.io/BoAT-X-Framework](https://aitos-io.github.io/BoAT-X-Framework)查看。
另外，boatiosdk-M5311-dev分支是我们的新功能开发分支，新功能开发完成后会合并到主分支并发布相应版本，查看BoAT相关文档时，应以主分支为准。
