### ISSUE TITLE
no uniform alignment in "boattypes.h"

### ISSUE THREAD

**Issue by zyq55917** [aitos-io/BoAT-X-Framework#443]
![2](https://user-images.githubusercontent.com/88825541/144191443-7d325d03-c4e9-4cce-8b76-eca40ce431e2.png)

**Comment by wsdhrtjl** [comment]
The reason for this problem is that the TAB key does not have four indent Spaces. Consider modifying the amount of indentation for local projects. The TAB will not be replaced with four spaces for the moment.
