### ISSUE TITLE
make error  incompatible type for argument 2 of 'BoatSignature'

### ISSUE THREAD

**Issue by SimonHe2021** [aitos-io/BoAT-X-Framework#5]
**To Reproduce**
pull the latest code, make error  incompatible type for argument 2 of 'BoatSignature'

see next error log:
boatethereum.c:286:43: error: incompatible type for argument 2 of 'BoatSignature'
  286 |           tx_ptr->wallet_ptr->account_info.prikeyId,
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
      |                                           |
      |                                           BoatWalletPriKeyId {aka struct TBoatWalletPriKeyId}

**Comment by woniua** [comment]
Hi
yes，because we had adjust the structure releated wallet, this problem will be resolved soon. @SimonHe2021

**Comment by SimonHe2021** [comment]
OK, I will watch the commits. @woniua

**Comment by yan-spring** [comment]
is solved this bug?

**Comment by woniua** [comment]
yes it is fixed
