### ISSUE TITLE
Open <YanFei Root>/cmake/toolchain-gcc.cmake Add the following two lines as below:

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#511]
**Describe the bug**
Open <YanFei Root>/cmake/toolchain-gcc.cmake Add the following two lines as below:

Kindly add "code " if applicable:
Open <YanFei Root>/cmake/toolchain-gcc.cmake Add the following two lines of code as below:

**Comment by zzqAlex** [comment]
Already adopted.
