### ISSUE TITLE
BoAT-X Framework for China Unicom YanFei-CUIot-MZ-6 Integration Guideline-  inconsistent  translation from Chinese version

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#512]
**Describe the bug**
For "添加BoAT-X-Framework lib文件到target_link_libraries" the translation is "Add the link to the BoAT-X-Framework libs"
https://github.com/aitos-io/BoAT-X-Framework/blob/boatiotsdk_2_0-dev/vendor/platform/YanFei-CUIot-MZ-6/README_en.md

Kindly update the English translation when you have time:
Add "BoAT-X-Framework lib" file to "target_link_libraries"

**Comment by zzqAlex** [comment]
Already adopted.
