### ISSUE TITLE
memory leak of platone  BoatPlatoneTxInit   abi_setName   my_contract_cpp_abi_setName

### ISSUE THREAD

**Issue by alanmoleapfive** [aitos-io/BoAT-X-Framework#529]
**Describe the bug**

Kindly include following information if applicable:
1. The commit id or tag on which you find the bug
2. The blockchain on which you find the bug
3. The smart contract on which you find the bug

**To Reproduce**
1. Configure ...
2. Call ...
3. Call ...

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and printed log to help explain your problem.

**Device (please complete the following information):**
 - Device brand and model: [e.g. Quectel EC20]
 - Chip model: [e.g. Qualcomm MDM9207]
 - OS: [e.g. linux]
 - Other information that may help [e.g. connect to Internet via 4G or 5G mobile network]

**Additional context**

**Comment by wsdhrtjl** [comment]
Reference to issue #482 #485 #487,  A number of memory leaks were fixed in the new version released last Friday. You can download the new version and see if it fixes the problem.

**Comment by alanmoleapfive** [comment]
Yes, it's fixed, thanks a lot for the prompt fix
