### ISSUE TITLE
BoatGetTimes fuction may be get wrong time on 32-bit Linux platforms.

### ISSUE THREAD

**Issue by wsdhrtjl** [aitos-io/BoAT-X-Framework#541]
The fuction is in file 'vendor\platform\linux-default\src\port_mbedtls\boatplatform.c'.
```
BUINT64 BoatGetTimes()
{
	BUINT64 timesec = 0;
	time(&timesec);
	return timesec;
}
```

The following error is reported during compilation:  
`In file included from boatplatform.c:24:
/usr/include/time.h:59:25: note: expected ‘time_t *’ {aka ‘long int *’} but argument is of type ‘BUINT64 *’ {aka ‘long long unsigned int *’}`

The fuction `time(&timesec);` use type long as input.
For 32-bit Linux platforms, the long is 4 bytes.
For 64-bit Linux platforms, the long is 8 bytes.

Since Linux is a small-end operating system, this conversion works fine, but it is uncertain whether it will cause an overflow.

**Comment by Cavalierliu** [comment]
problem fixed
