### ISSUE TITLE
Some .DS_Store files appear in the code folders

### ISSUE THREAD

**Issue by PanHH** [aitos-io/BoAT-X-Framework#545]
**Describe the bug**
Some .DS_Store files appear in the code folders, suggest to remove them.

1. BoAT-X-Framework/.DS_Store
2. BoAT-X-Framework/vendor/.DS_Store
3. BoAT-X-Framework/vendor/platform/.DS_Store
4. BoAT-X-Framework/vendor/platform/Fibocom-MA510/.DS_Store
5. BoAT-X-Framework/vendor/platform/Fibocom-MA510/src/.DS_Store

**Comment by zzqAlex** [comment]
All .DS_Store files have been removed.
