### ISSUE TITLE
BoatFiscobcosTxInit     when multiple transactions

### ISSUE THREAD

**Issue by alanmoleapfive** [aitos-io/BoAT-X-Framework#546]
"blocklimit":"0x202"    "blocklimit":"0x202"  "blocklimit":"0x202"  no   change   
have   Failed
 [BOAT DBG]httpclient_close() client:0x42013d30LOG_NORMAL: web3intf.c:96, web3_parse_json_result(): Cannot find "result" item in RESPONSE.
                                                                                                                                          LOG_NORMAL: web3intf.c:173, web3_parse_json_result(): Exception: -10700001
                                                      LOG_NORMAL: boatfiscobcos.c:464, FiscobcosSendRawtx(): Fail to prase RPC response.
                                                                                                                                        LOG_CRITICAL: boatfiscobcos.c:477, FiscobcosSendRawtx(): Exception: -10700001

 fisco mycontract access Failed: -1.

**Comment by wsdhrtjl** [comment]
see issue #313
This part is mainly about the incorrect parsing of the response. This part is mainly about the incorrect parsing of the response. This does not currently affect calls to the Fiscobcos chain.
