### ISSUE TITLE
Some anchor points in the user manual are not completed

### ISSUE THREAD

**Issue by GHKG** [aitos-io/BoAT-X-Framework#554]
_例如：_
由于合约编程语言一般支持面向对象，而C语言不支持面向对象，无法使用统一范式传递对象，因此只有参数类型与C语言内置类型一致的合约函数，可以通过工具转换为C调用代码。具体的支持合约函数输入类型详见**合约调用（自动生成）** 章节。

**Comment by wsdhrtjl** [comment]
每个标题是一个链接。造成不能跳转的原因是当前链接和跳转指向的链接是同一个，所以不会触发跳转。当前链接如果是其他的话，可以正常跳转。
