### ISSUE TITLE
make demo should stop when Python is not found

### ISSUE THREAD

**Issue by IDvochen** [aitos-io/BoAT-X-Framework#57]
**Describe the bug**
Make demo reports boatconfig.h not found. Since Python is not found in the environment (named Python3 by default on Ubuntu), the make procedure should stop as soon as it gets the Python-not-found issue.

**Screenshots and log**
~/Documents/BoAT-X-Framework-master$ make demo
/bin/sh: 1: python: not found
generate header file boatconfig.h...
generate done.
mkdir -p /home/lian/Documents/BoAT-X-Framework-master/lib
mkdir -p /home/lian/Documents/BoAT-X-Framework-master/build
if [ -d "/home/lian/Documents/BoAT-X-Framework-master/sdk" ]; then \
make -C /home/lian/Documents/BoAT-X-Framework-master/sdk all; \
fi
make[1]: Entering directory '/home/lian/Documents/BoAT-X-Framework-master/sdk'
make -C utilities all
make[2]: Entering directory '/home/lian/Documents/BoAT-X-Framework-master/sdk/utilities'
cc -c -ffunction-sections -fdata-sections -I/home/lian/Documents/BoAT-X-Framework-master/include -I/home/lian/Documents/BoAT-X-Framework-master/sdk -I/home/lian/Documents/BoAT-X-Framework-master/sdk/include -I/home/lian/Documents/BoAT-X-Framework-master/sdk/platform -I/home/lian/Documents/BoAT-X-Framework-master/sdk/protocol -I/home/lian/Documents/BoAT-X-Framework-master/sdk/protocol/common/http2intf -I/home/lian/Documents/BoAT-X-Framework-master/sdk/protocol/common/web3intf -I/home/lian/Documents/BoAT-X-Framework-master/sdk/protocol/boathlfabric -I/home/lian/Documents/BoAT-X-Framework-master/sdk/protocol/boathlfabric/protos -I/home/lian/Documents/BoAT-X-Framework-master/sdk/protocol/boatethereum -I/home/lian/Documents/BoAT-X-Framework-master/sdk/protocol/boatplatone -I/home/lian/Documents/BoAT-X-Framework-master/sdk/protocol/boatfiscobcos -I/home/lian/Documents/BoAT-X-Framework-master/sdk/third-party/cJSON -I/home/lian/Documents/BoAT-X-Framework-master/sdk/third-party/nghttp2/include -I/home/lian/Documents/BoAT-X-Framework-master/sdk/third-party/protobuf-c/include -I/home/lian/Documents/BoAT-X-Framework-master/vendor/platform/include -I/home/lian/Documents/BoAT-X-Framework-master/vendor/platform/LINUX-X86-64/src/log -I/home/lian/Documents/BoAT-X-Framework-master/contract/generated -I/home/lian/Documents/BoAT-X-Framework-master/demo -I/home/lian/Documents/BoAT-X-Framework-master/tests  -I/home/lian/Documents/BoAT-X-Framework-master/vendor/common/crypto/crypto_default -I/home/lian/Documents/BoAT-X-Framework-master/vendor/common/crypto/crypto_default/aes -I/home/lian/Documents/BoAT-X-Framework-master/vendor/common/crypto/keccak -I/home/lian/Documents/BoAT-X-Framework-master/vendor/common/storage -I/home/lian/Documents/BoAT-X-Framework-master/vendor/platform/LINUX-X86-64/port_crypto_default -std=c99 -Os -Wall    boatutility.c -o /home/lian/Documents/BoAT-X-Framework-master/build/sdk/utilities/boatutility.o
In file included from /home/lian/Documents/BoAT-X-Framework-master/sdk/include/boatinternal.h:36,
                 from boatutility.c:23:
/home/lian/Documents/BoAT-X-Framework-master/vendor/platform/include/boatplatform_internal.h:27:10: fatal error: boatconfig.h: No such file or directory
   27 | #include "boatconfig.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:14: /home/lian/Documents/BoAT-X-Framework-master/build/sdk/utilities/boatutility.o] Error 1
make[2]: Leaving directory '/home/lian/Documents/BoAT-X-Framework-master/sdk/utilities'
make[1]: *** [Makefile:43: utilities] Error 2
make[1]: Leaving directory '/home/lian/Documents/BoAT-X-Framework-master/sdk'
make: *** [Makefile:190: boatwalletlib] Error 2

**Comment by woniua** [comment]
Hi
Thanks for your suggestion, it is valuable advice! It will be discussed that add dependent environment check before releated tools be invoked.
