### ISSUE TITLE
Ethereum test code compile error

### ISSUE THREAD

**Issue by xunzhu0507** [aitos-io/BoAT-X-Framework#587]
When only set BOAT_PROTOCOL_USE_ETHEREUM = 1 in the makefile, the Ethereum test code can be compiled. if set BOAT_PROTOCOL_USE_PLATON = 1 or BOAT_PROTOCOL_USE_PLATONE = 1, the Ethereum test code can not be compiled.

**Comment by PanHH** [comment]
It must be this way.
