### ISSUE TITLE
module list BoAT supported

### ISSUE THREAD

**Issue by linyao0177** [aitos-io/BoAT-X-Framework#59]
Is there an updated list of cellular modules or IoT chipset platforms BoAT already supported and plan to support?

**Comment by flyfft** [comment]
Add [SUPPORTED_LIST.md](/SUPPORTED_LIST.md) and refer to it in README.md in [Release BoAT-X-v2.0.2](https://github.com/aitos-io/BoAT-X-Framework/releases/tag/BoAT-X-v2.0.2)
