### ISSUE TITLE
How the wallet is stored if terminal device don't support file systems

### ISSUE THREAD

**Issue by SimonHe2021** [aitos-io/BoAT-X-Framework#6]
The wallet is stored in a file, 
Once the terminal device don't support file systems, How the wallet is stored?

In this way, It can be stored in the flash.
I think we can modify the following functions:
BOAT_RESULT  BoatReadFile( const BCHAR *fileName, 
						   BUINT8 *readBuf, BUINT32 readLen, void* rsvd );

BOAT_RESULT  BoatWriteFile( const BCHAR *fileName, 
						    BUINT8* writeBuf, BUINT32 writeLen, void* rsvd );

**Comment by woniua** [comment]
Yes you are right. 
This function is an abstraction for accessing EVM, and the default implementation is with a file system, this function needs to be rewritten when porting to platforms that do not support file systems.
