### ISSUE TITLE
BoAT_User_Guide_en --better expression

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#611]
**Describe the bug**
区块链钱包创建/加载/卸载/删除
Blockchain account creation/loading/unloading

Kindly refine the English expression if possible:

Blockchain account creation/Import/uninstallation

**Comment by flyfft** [comment]
Creation: The operation that establish the account context in RAM and optionally permanently store a copy of the context in non-volatile RAM. An account context consists of the blockchain protocol, the chain ID, the URL to the blockchain node, the private key etc.
