### ISSUE TITLE
BoAT_User_Guide_en-PlatONE should be replaced by Venachain

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#613]
**Describe the bug**
![image](https://user-images.githubusercontent.com/76994415/160621606-71496019-ef64-49e9-bda3-0cc0ee9d6592.png)

Kindly refine the description:
I see PlatONE in our architecture, please update it with Venachain.

[BoAT IoT Framework SDK Architecture](https://aitos-io.github.io/BoAT-X-Framework/#/en-us/BoAT_User_Guide_en?id=boat-iot-framework-sdk-architecture)

**Comment by zzqAlex** [comment]
I think PlatONE and VenaChain are in a juxtaposition.
