### ISSUE TITLE
Add medium and linkedin hyperlink in the introduction page

### ISSUE THREAD

**Issue by linyao0177** [aitos-io/BoAT-X-Framework#64]
Add medium and linkedin hyperlink in the introduction page to give community members an overview of BoAT's market activities.

**Comment by flyfft** [comment]
Add hyperlink for Medium and LinkedIn in README.md's Community section in this [commit](https://github.com/aitos-io/BoAT-X-Framework/commit/f45f20e315480e3f710ad0cb7eb193d4b3737620).
