### ISSUE TITLE
The platone demo cannot be executed successfully

### ISSUE THREAD

**Issue by zzqAlex** [aitos-io/BoAT-X-Framework#640]
**Describe the bug**
When I run the demo of platone on the PC, the following error is reported：
<img width="884" alt="WechatIMG315" src="https://user-images.githubusercontent.com/44628575/163530122-79dfce5d-4d91-44ad-a1ed-70bda31ea49c.png">

**Comment by wsdhrtjl** [comment]
CURLcode 7: failed to connect.
Check that the link is correct or not.
