### ISSUE TITLE
I got "404" error page when I click the hyperLink

### ISSUE THREAD

**Issue by DongAoMainland** [aitos-io/BoAT-X-Framework#663]
When I click the HyperLink in the page "https://github.com/aitos-io/BoAT-X-Framework/tree/release-v2.1.10/docs/en-us", "404" error page would come out.

The HyperLinks are at the bottom of page which is the part of document readme.md.
 
You can click "[BoAT User Guide](https://github.com/aitos-io/BoAT-X-Framework/blob/release-v2.1.10/en-us/BoAT_User_Guide_en.md)", and get what I mean.

**Comment by wsdhrtjl** [comment]
This problem is caused by the path format. To ensure that links within [BoAT-X documentations](https://aitos-io.github.io/BoAT-X-Framework/#/) are available, this cannot be modified.
