### ISSUE TITLE
A little problem in BoAT_User_Guide_cn.md

### ISSUE THREAD

**Issue by zzqAlex** [aitos-io/BoAT-X-Framework#667]
**Describe the bug**
Location:/boatiotsdk_2_0-dev/docs/zh-cn/BoAT_User_Guide_cn.md
venachain is not added to the list of supported chains in BoAT_User_Guide_cn.md.

**Comment by utkarshsingx** [comment]
I would like to work on this, can you please elucidate the issue here.
