### ISSUE TITLE
two link failures on the page “https://github.com/aitos-io/BoAT-X-Framework/tree/master/docs”

### ISSUE THREAD

**Issue by GHKG** [aitos-io/BoAT-X-Framework#670]
![1](https://user-images.githubusercontent.com/16286394/164363602-79e88e4f-259e-4d93-af12-0d13cd81976d.png)

**Comment by wsdhrtjl** [comment]
This problem is caused by the path format. To ensure that links within [BoAT-X documentations](https://aitos-io.github.io/BoAT-X-Framework/#/) are available, this cannot be modified.
