### ISSUE TITLE
The Hyperlink can not bring out the right page/

### ISSUE THREAD

**Issue by DongAoMainland** [aitos-io/BoAT-X-Framework#697]
When we use right button of mouse to open the hyperlink "[Contract Call (Automatically Generated)](https://aitos-io.github.io/BoAT-X-Framework/#/en-us/BoAT_User_Guide_en?id=contract-call-(automatically-generated))", we would arrive at "https://aitos-io.github.io/BoAT-X-Framework/#/en-us/BoAT_User_Guide_en", why not come to the "contract-call-(automatically-generated)" directly?

**Comment by PanHH** [comment]
Same issue to #696.
