### ISSUE TITLE
"SDK Initialization/Deinitialization" missing hyperlink

### ISSUE THREAD

**Issue by zyq55917** [aitos-io/BoAT-X-Framework#702]
https://github.com/aitos-io/BoAT-X-Framework/blob/master/docs/en-us/BoAT_Overall_Design_en.md
BoAT SDK initialization: Please refer to the description of "BoAT SDK Initialization" in SDK Initialization/Deinitialization

**Comment by PanHH** [comment]
Same issue with #400
