### ISSUE TITLE
Test case error - undefined reference to 'BoatHlchainmakerTxInit'

### ISSUE THREAD

**Issue by PanHH** [aitos-io/BoAT-X-Framework#724]
**Describe the bug**
When I run the chainmaker test cases, I got the below error.
![1651919809(1)](https://user-images.githubusercontent.com/26243670/167250712-d1b8b8f0-0bac-41f8-9bdd-40d4fda0f999.png)

**Comment by Cavalierliu** [comment]
Code updated, problem solved
