### ISSUE TITLE
Test case error - undefined reference to 'BoatHlchainmakerContractQuery'

### ISSUE THREAD

**Issue by PanHH** [aitos-io/BoAT-X-Framework#725]
**Describe the bug**
When I run the chainmaker test cases, I got the below error.

![1651919960(1)](https://user-images.githubusercontent.com/26243670/167250793-1f666529-2ab3-44b7-83c4-7e8c46acb6f7.png)

**Comment by Cavalierliu** [comment]
Code updated, problem solved
