### ISSUE TITLE
the hyper link has no effect about “Transaction initialization”

### ISSUE THREAD

**Issue by DongAoMainland** [aitos-io/BoAT-X-Framework#775]
when we click the hyperlink about "Transaction initialization" in the document BoAT_Overall_Design_en (https://github.com/aitos-io/BoAT-X-Framework/blob/release-v2.2.0/docs/en-us/BoAT_Overall_Design_en.md)，there has no any response.

**Comment by PanHH** [comment]
Same issue with #703
