### ISSUE TITLE
Typo in source code: include/boatutility.h

### ISSUE THREAD

**Issue by masstensor** [aitos-io/BoAT-X-Framework#786]
//line 20
remove the "boatwallet" word?

//line32 
utility boat utility --> BoAT utility functions?

KEYPAIT_ALG //no API document
TLVStruct //no API document
KeypairNative //no API document

Function <UtilityTrimBin>'s parameters no in/out tag, for example:
@param to_ptr --> @param[out] to_ptr
@param from_ptr --> @param[in] from_ptr
@param from_len --> @param[in] from_len
@param trim_mode --> @param[in] trim_mode
@param zero_as_null --> @param[in] zero_as_null

**Comment by zzqAlex** [comment]
The content has been re-adjusted.
