### ISSUE TITLE
In compiling and running the Demo, the link pointed to by "use Windows as the compilation environment" does not jump to the corresponding content

### ISSUE THREAD

**Issue by hnngm** [aitos-io/BoAT-X-Framework#802]
**Describe the bug**
In compiling and running the Demo, the link pointed to by "use Windows as the compilation environment" does not jump to the corresponding content
[以Windows为编译环境](https://github.com/aitos-io/BoAT-X-Framework/tree/master/demo####%E4%BB%A5Windows%E4%B8%BA%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83)

**Comment by PanHH** [comment]
Same with #699
