### ISSUE TITLE
There is not space between title and url

### ISSUE THREAD

**Issue by blockchainzk** [aitos-io/BoAT-X-Framework#84]
https://github.com/aitos-io/BoAT-X-Framework/blob/master/docs/en-us/BoAT_Overall_Design_en.md

the **_Reference_** part of document.

[1]. cJSONhttps://github.com/DaveGamble/cJSON#welcome-to-cjson
[2]. cURLhttps://curl.haxx.se/libcurl/

**Comment by wsdhrtjl** [comment]
Thanks for point this.I fix this in commit c94ee388e495ac7924d5cd9511403ca5f4780c15.
