### ISSUE TITLE
BoAT系统需求-Please complete the related scenarios

### ISSUE THREAD

**Issue by mia-BoAT-Mariner** [aitos-io/BoAT-X-Framework#932]
**Describe the bug**

支持以太坊/PlatONE/FISCO BCOS时，BoAT至少需要如下密码学运算：

椭圆曲线签名ECDSA（secp256k1曲线）
Keccak-256（Keccak-256为SHA3-256的变种）

仅支持以太坊/Venachain/FISCO BCOS时，BoAT Framework SDK（C语言版本）自身对存储的需求约为：

Flash（代码和只读数据）：约210kB
Flash（持久性读写数据）：数百Bytes
RAM（全局变量、堆、栈）：约10kB

Kindly include following information if applicable:
支持以太坊/PlatONE/FISCO BCOS时，BoAT至少需要如下密码学运算：---How about "Venachain"
仅支持以太坊/Venachain/FISCO BCOS时，BoAT Framework SDK（C语言版本）自身对存储的需求约为：---How about "PlatONE"

**Comment by PanHH** [comment]
Unified as Venachain
