### ISSUE TITLE
方法UtilityStringIsHex的注释中的参数名称与方法中的参数名称不一致

### ISSUE THREAD

**Issue by xymoc** [aitos-io/BoAT-X-Framework#976]
在dev2.0分支中的include/boatutility.h文件内，第609行的UtilityStringIsHex方法注释中的参数名称与方法中的参数名称不一致，注释中的参数名为“mem”，方法中的参数名为“input”。

**Comment by zzqAlex** [comment]
You're right, it's been corrected.
