### ISSUE TITLE
Two paragraphs of text in the same paragraph are replaced by two lines

### ISSUE THREAD

**Issue by hnngm** [aitos-io/BoAT-X-Framework#996]
[problem location](https://aitos-io.github.io/BoAT-X-Framework/#/en-us/BoAT_User_Guide_en?id=programming-model)

"Among them, the format of rlp_param_ptr follows the same rules as Step 3." and  “For the specific calling method, please refer to the automatically generated....”，These two paragraphs should be in one paragraph, now it shows line breaks

**Comment by wsdhrtjl** [comment]
These two sentences should be separated, but the second sentence is not formatted correctly. Also, the path in the second sentence is incorrect.
